model:
  filename: ./gen/models_gen.go
client:
  filename: ./gen/client.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  Date:
    model: github.com/99designs/gqlgen/graphql.Time
endpoint:
  url: https://api.annict.com/graphql
  headers:
    Authorization: "Bearer ${ANNICT_KEY}"
query:
  - "./query/*.graphql"
generate:
  clientV2: true
  suffix:
    mutation: Payload
  prefix:
    mutation: Hoge
